### ISSUE TITLE
Plugin execution not covered - resources

### ISSUE THREAD

**Issue by washowasho** [spirylics/x-gwt#4]
The below is happening on all projects, except for the server project. I don't think resources is a valid execution. 

`Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:gwt-maven-plugin:2.8.0:resources (execution: default, phase: process-resources)	pom.xml	/x-gwt-all	line 64	Maven Project Build Lifecycle Mapping Problem`

**Comment by washowasho** [comment]
It's deprecated per this link:

https://gwt-maven-plugin.github.io/gwt-maven-plugin/resources-mojo.html

**Comment by spirylics** [comment]
Thanks for reporting
